# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a00b57d08c2edd01b4407e09e872db7c8d00cb36aa67fbfa51ed9d36f6d57a39e428e50ac03a1cada8a6030a3d39ff0fdfdacf1123587ea451990f1eed962901

test:
  secret_key_base: 5ad125803a1f98c46f78ee4f346dcbd988b35dd40c88354111b9336fc529d0b74b920d47412f901c2c1ebc4d54dc234746ee429379b7b07fc6ca7baafceb43da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
